name: 'OptCD tool'
description: 'Demo tool for OptCD'

inputs:
  yaml-file:
    description: 'YAML file to be modified'
    required: true

#outputs:
#  unnecessary-folders:
#    description:
#    value:
#  responsible-plugins:
#    description:
#    value:

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "${{ github.action_path }}"/requirements.txt
      shell: bash
    - run: python "${{ github.action_path }}"/main.py "${{ inputs.yaml-file }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
