name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: 3.7
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    - name: Run base action
      uses: ogul1/base-action@main
      with:
        yaml-file: .github/workflows/example.yml
    - name: add code to push results to another repository
    name: 'Build'
