name: Cucumber CI
on: [push]
jobs:
   build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps  :
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-${{ runner.os }}-maven-
      - uses:
          AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
      - name: test maven
        run: |
          cd maven
          ./mvnw test -Dmaven.test.failure.ignore
      - run: grep -q "The step 'I wait 1 hour' and 1 other step(s) are undefined." maven/target/surefire-reports/io.cucumber.skeleton.RunCucumberTest.txt || ( echo "mvn test didn't fail as expected" && false )
      - name: test gradle
        run: |
          cd gradle
          ./gradlew test || true
      - run: grep -q "The step 'I wait 1 hour' and 1 other step(s) are undefined." gradle/build/reports/tests/test/classes/io.cucumber.skeleton.RunCucumberTest.html  || ( echo "gradle test didn't fail as expected" && false )
      - name: compare gradle and maven sources
        run: diff gradle/src maven/src
      - name: add code to push results to another repository
   build2:
        runs-on: ubuntu-latest
        steps  :
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pandas
            pip install numpy
        - run: sudo apt update
        - run: sudo apt install inotify-tools
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
                    python-version: "3.7"
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run a multi-line script
          run: |
           echo Add other actions to build,
           echo test, and deploy your project.
        - name: Run base action
          uses: ogul1/base-action@main
          with:
          yaml-file: .github/workflows/example.yml
        -     name: My first step
              run: echo This event is a pull request that had an assignee removed.
        -         run: echo 'This step will only run if the secret has a value set.'
        -     run: echo 'This step will only run if the secret does not have a value set.'
        -   run: echo This event is a pull request that had an assignee removed.
        - name: add code to push results to another repository
